Models/ErrorViewModel.cs
namespace Info_ToolsCRUD_SP_Imgs.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Imagen.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Info_ToolsCRUD_SP_Imgs.Models
{
    public class Imagen
    {
        [Key]
        public int Id_Imagen { get; set; }
        public DateTime Fecha_Creacion { get; set; } = DateTime.Now;
        public string? Nombre { get; set; }
        public string? Image { get; set; }

        [NotMapped]
        public IFormFile? File { get; set; } // Indicador oara saber si la imagen ha sido cargada
    }
}

Controllers/HomeController.cs
using Info_ToolsCRUD_SP_Imgs.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Info_ToolsCRUD_SP_Imgs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LibroController.cs
using Info_ToolsCRUD_SP_Imgs.Data;
using Info_ToolsCRUD_SP_Imgs.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;

namespace Info_ToolsCRUD_SP_Imgs.Controllers
{
    public class LibroController : Controller
    {
        private readonly ApplicationDBContext _DbContext;
        public LibroController(ApplicationDBContext _dbContext)
        {
            _DbContext = _dbContext;
        }

        public IActionResult Index()
        {
            using (SqlConnection conexion = new SqlConnection(_DbContext.Conexion))
            {
                List<Imagen> ListaImagenes = new List<Imagen>();
                using (SqlCommand cmd = new SqlCommand("sp_Listar", conexion))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    conexion.Open();

                    var rd = cmd.ExecuteReader();

                    while (rd.Read())
                    {
                        ListaImagenes.Add(new Imagen
                        {
                            Id_Imagen = (int)rd["Id_Imagen"],
                            Fecha_Creacion = (DateTime)rd["Fecha_Creacion"],
                            Nombre = rd["Nombre"].ToString(),
                            Image = rd["Imagen"].ToString()
                        });
                    }
                }
                return View(ListaImagenes);
            }
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Imagen imagen)
        {
            try
            {
                byte[] bytes;
                if (imagen.File != null && imagen.Nombre != null)
                {
                    using (Stream fs = imagen.File.OpenReadStream())
                    {
                        using (BinaryReader br = new(fs))
                        {
                            bytes = br.ReadBytes((int)fs.Length);
                            imagen.Image = Convert.ToBase64String(bytes, 0, bytes.Length);

                            using (SqlConnection conexion = new SqlConnection(_DbContext.Conexion))
                            {
                                using (SqlCommand cmd = new SqlCommand("sp_Crear", conexion))
                                {
                                    cmd.CommandType = CommandType.StoredProcedure;
                                    cmd.Parameters.AddWithValue("Fecha_Creacion", imagen.Fecha_Creacion);
                                    cmd.Parameters.AddWithValue("Nombre", imagen.Nombre);
                                    cmd.Parameters.AddWithValue("Imagen", imagen.Image);
                                    conexion.Open();
                                    cmd.ExecuteNonQuery();
                                    conexion.Close();
                                }
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View(imagen);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            using (SqlConnection conexion = new(_DbContext.Conexion))
            {
                Imagen registro = new Imagen();
                using (SqlCommand cmd = new("sp_Buscar", conexion))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("Id_Imagen", id);
                    conexion.Open();

                    SqlDataAdapter da = new(cmd);
                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    registro.Id_Imagen = (int)dt.Rows[0][0];
                    registro.Nombre = dt.Rows[0][2].ToString();
                    registro.Image = dt.Rows[0][3].ToString();
                }
                return View(registro);
            }
        }

        [HttpPost]
        public IActionResult Editar(Imagen imagen)
        {
            try
            {
                using (SqlConnection conexion = new(_DbContext.Conexion))
                {
                    string i; // Validacion si una imagen ha sido cargada
                    if (imagen.File == null)
                        i = "null";
                    else
                    {
                        byte[] bytes;
                        // Conversión de imagen a formato que se pueda almacenar
                        using (Stream fs = imagen.File.OpenReadStream())
                        {
                            using (BinaryReader br = new(fs))
                            {
                                bytes = br.ReadBytes((int)fs.Length);
                                i = Convert.ToBase64String(bytes, 0, bytes.Length);
                            }
                        }
                    }

                    using (SqlCommand cmd = new("sp_Actualizar", conexion))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("Id_Imagen", imagen.Id_Imagen);
                        cmd.Parameters.AddWithValue("Nombre", imagen.Nombre);
                        cmd.Parameters.AddWithValue("Imagen", i);
                        conexion.Open();
                        cmd.ExecuteNonQuery();
                        conexion.Close();
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View(imagen);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            using (SqlConnection conexion = new(_DbContext.Conexion))
            {
                Imagen registro = new Imagen();
                using (SqlCommand cmd = new("sp_Buscar", conexion))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("Id_Imagen", id);
                    conexion.Open();

                    SqlDataAdapter da = new(cmd);
                    DataTable dt = new DataTable();
                    da.Fill(dt);
                    registro.Id_Imagen = (int)dt.Rows[0][0];
                    registro.Nombre = dt.Rows[0][2].ToString();
                    registro.Image = dt.Rows[0][3].ToString();
                }
                return View(registro);
            }
        }

        [HttpPost]
        public IActionResult Eliminar(Imagen imagen)
        {
            using (SqlConnection conexion = new(_DbContext.Conexion))
            {
                using SqlCommand cmd = new("sp_Eliminar", conexion);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("Id_Imagen", imagen.Id_Imagen);
                conexion.Open();
                cmd.ExecuteNonQuery();
                conexion.Close();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Libro/Crear.cshtml
@model Info_ToolsCRUD_SP_Imgs.Models.Imagen

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<form enctype="multipart/form-data" asp-action="Crear" asp-controller="Libro" class="container" method="post">
    <h3>Insertar registros</h3>
    <table class="table">
        <tr>
            <td>
                <label class="form-label">Nombre: </label>
            </td>
            <td>
                <input class="form-control" type="text" required asp-for="Nombre" />
            </td>
        </tr>

        <tr>
            <td>
                <label class="form-label">Imagen: </label>
            </td>
            <td>
                <input class="form-control" type="file" required asp-for="File" />
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <input type="submit" class="btn btn-success" value="Crear" />
            </td>
        </tr>
    </table>

</form>

<a class="btn btn-primary" asp-action="Index" asp-controller="Libro">Volver</a>

<label class="alert-danger">@ViewBag.error</label>

Views/Libro/Editar.cshtml
@model Info_ToolsCRUD_SP_Imgs.Models.Imagen

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<form enctype="multipart/form-data" asp-action="Editar" asp-controller="Libro" class="container-fluid" method="post">
    <div class="card mb-6">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="data:img/jpg; base64, @Model.Image" class="rounded" width="400">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Registro</h5>
                    <table class="table">
                        <input class="form-control" type="hidden" asp-for="Fecha_Creacion" />
                        <input class="form-control" type="hidden" asp-for="Id_Imagen" />
                        <tr>
                            <td>
                                <label class="form-label">Nombre: </label>
                            </td>
                            <td>
                                <input class="form-control" type="text" required asp-for="Nombre" />
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label class="form-label">Imagen: </label>
                            </td>
                            <td colspan="2">
                                <input class="form-control" type="file" required asp-for="File" />
                            </td>
                        </tr>

                        <tr>
                            <td colspan="2">
                                <input type="submit" class="btn btn-success" value="Actualizar" />
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>

<a class="btn btn-primary" asp-action="Index" asp-controller="Libro">Volver</a>

Views/Libro/Eliminar.cshtml
@model Info_ToolsCRUD_SP_Imgs.Models.Imagen

@{
    ViewData["Title"] = "Eliminar";
}

<h1>¿Eliminar?</h1>

<form enctype="multipart/form-data" asp-action="Eliminar" asp-controller="Libro" class="container-fluid" method="post">
    <div class="card mb-6">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="data:img/jpg; base64, @Model.Image" class="rounded" width="400">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Registro</h5>
                    <table class="table">
                        <input class="form-control" type="hidden" asp-for="Fecha_Creacion" />
                        <input class="form-control" type="hidden" asp-for="Id_Imagen" />
                        <tr>
                            <td>
                                <label class="form-label">Nombre: </label>
                            </td>
                            <td>
                                <input class="form-control" type="text" disabled asp-for="Nombre" />
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <label class="form-label">Fecha de creación: </label>
                            </td>
                            <td>
                                <input class="form-control" type="text" disabled asp-for="Fecha_Creacion" />
                            </td>
                        </tr>

                        <tr>
                            <td colspan="2">
                                <input type="submit" class="btn btn-danger" value="Eliminar" />
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>

<a class="btn btn-primary" asp-action="Index" asp-controller="Libro">Volver</a>

Views/Libro/Index.cshtml
@model List<Info_ToolsCRUD_SP_Imgs.Models.Imagen>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<a asp-action="Crear" asp-controller="Libro" class="btn btn-outline-primary">Crear</a>
<br />
<br />

@if (Model.Count() > 0)
{
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var item in Model)
        {
             <div class="col">
                <div class="card h-100">
                    <img src="data:img/jpg; base64, @item.Image" style="max-height:30vh; object-fit:contain;" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@item.Nombre</h5>
                        <p class="card-text">@item.Fecha_Creacion</p>
                    </div>
                    <div class="card-footer">
                        <a type="button" asp-action="Editar" asp-controller="Libro" class="btn-sm btn-outline-warning" asp-route-id="@item.Id_Imagen">Editar</a>
                        <a type="button" asp-action="Eliminar" asp-controller="Libro" class="btn-sm btn-outline-danger" asp-route-id="@item.Id_Imagen">Eliminar</a>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="alert alert-danger" role="alert">
        No hay datos para mostrar
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Info_ToolsCRUD_SP_Imgs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Info_ToolsCRUD_SP_Imgs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Info_ToolsCRUD_SP_Imgs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Index">Imágenes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Info_ToolsCRUD_SP_Imgs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>